### ISSUE TITLE
Example Code Fails

### ISSUE THREAD

**Issue by emanual4real** [allelos/vectors#2]
I'm fairly new to Python and tried to use your Vector package.  I'm a fan of linear algebra.  I can't seem to get your examples to work though.

```from vectors import Point, Vector

v1 = Vector(1, 2, 3)

print(v1.magnitude())
```
Yields the below error.  I'm on Python 3.6
```
  File "C:\Python36-32\lib\site-packages\vectors\vectors.py", line 52, in magnitude
    return (math.sqrt(reduce(lambda x, y: x+y,
NameError: name 'reduce' is not defined
```
Thanks
Manny

**Comment by barbaBus** [comment]
The issue is that the "reduce" has been moved into functools library.
It is just necessary to add in the file vectors.py the following import command at the beginning:

from functools import reduce

**Comment by manan3172003** [comment]
I cannot use sum, dot product, cross product and many  other functions.
error: TypeError: 'list' object is not callable
